name: challenge
description: Challenge Nubimetrics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: "0.11.3+17"
  intl: ">=0.14.0"
  rxdart: ^0.25.0
  auto_size_text: ^2.1.0
  mask_text_input_formatter: ^1.2.1
  pattern_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

